[Uno.Compiler.UxGenerated]
public partial class c_gr: Fuse.Controls.Page
{
    readonly Fuse.Navigation.Router router;
    [Uno.Compiler.UxGenerated]
    public partial class Template: Uno.UX.Template
    {
        [Uno.WeakReference] internal readonly c_gr __parent;
        [Uno.WeakReference] internal readonly c_gr __parentInstance;
        public Template(c_gr parent, c_gr parentInstance): base(null, false)
        {
            __parent = parent;
            __parentInstance = parentInstance;
        }
        global::Uno.UX.Property<string> temp_Value_inst;
        global::Uno.UX.Property<string> temp1_Value_inst;
        global::Uno.UX.Property<string> temp2_Value_inst;
        global::Uno.UX.Property<string> temp3_Value_inst;
        static Template()
        {
        }
        public override object New()
        {
            var __self = new global::Fuse.Controls.DockPanel();
            var temp = new global::Fuse.Controls.Text();
            temp_Value_inst = new HSMRO_FuseControlsTextControl_Value_Property(temp, __selector0);
            var temp4 = new global::Fuse.Reactive.Data("gr_item_cd");
            var temp1 = new global::Fuse.Controls.Text();
            temp1_Value_inst = new HSMRO_FuseControlsTextControl_Value_Property(temp1, __selector0);
            var temp5 = new global::Fuse.Reactive.Data("gr_item_nm");
            var temp2 = new global::Fuse.Controls.Text();
            temp2_Value_inst = new HSMRO_FuseControlsTextControl_Value_Property(temp2, __selector0);
            var temp6 = new global::Fuse.Reactive.Data("po_no");
            var temp7 = new global::Fuse.Reactive.Data("gr_qty");
            var temp8 = " ";
            var temp9 = new global::Fuse.Reactive.Constant(temp8);
            var temp10 = new global::Fuse.Reactive.Data("gr_unit");
            var temp11 = new global::Fuse.Reactive.Add(temp9, temp10);
            var temp3 = new global::Fuse.Controls.Text();
            temp3_Value_inst = new HSMRO_FuseControlsTextControl_Value_Property(temp3, __selector0);
            var temp12 = new global::Fuse.Reactive.Add(temp7, temp11);
            var temp13 = new global::Fuse.Reactive.DataBinding(temp_Value_inst, temp4, Fuse.Reactive.BindingMode.Default);
            var temp14 = new global::Fuse.Reactive.DataBinding(temp1_Value_inst, temp5, Fuse.Reactive.BindingMode.Default);
            var temp15 = new global::Fuse.Reactive.DataBinding(temp2_Value_inst, temp6, Fuse.Reactive.BindingMode.Default);
            var temp16 = new global::Fuse.Reactive.DataBinding(temp3_Value_inst, temp12, Fuse.Reactive.BindingMode.Default);
            var temp17 = new global::Fuse.Triggers.LayoutAnimation();
            var temp18 = new global::Fuse.Animations.Move();
            var temp19 = new global::Fuse.Triggers.AddingAnimation();
            var temp20 = new global::Fuse.Animations.Move();
            var temp21 = new global::Fuse.Triggers.RemovingAnimation();
            var temp22 = new global::Fuse.Animations.Move();
            __self.Width = new Uno.UX.Size(100f, Uno.UX.Unit.Percent);
            __self.Height = new Uno.UX.Size(40f, Uno.UX.Unit.Unspecified);
            __self.Alignment = Fuse.Elements.Alignment.Default;
            __self.Margin = float4(0f, 1f, 0f, 1f);
            __self.Padding = float4(10f, 10f, 10f, 10f);
            __self.SourceLineNumber = 141;
            __self.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp.FontSize = 15f;
            temp.Width = new Uno.UX.Size(100f, Uno.UX.Unit.Unspecified);
            temp.MinWidth = new Uno.UX.Size(100f, Uno.UX.Unit.Unspecified);
            temp.MaxWidth = new Uno.UX.Size(130f, Uno.UX.Unit.Unspecified);
            temp.Alignment = Fuse.Elements.Alignment.Default;
            temp.SourceLineNumber = 142;
            temp.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            global::Fuse.Controls.DockPanel.SetDock(temp, Fuse.Layouts.Dock.Left);
            temp.Font = global::MainView.AGOTHIC14;
            temp.Bindings.Add(temp13);
            temp4.SourceLineNumber = 142;
            temp4.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp1.FontSize = 15f;
            temp1.Alignment = Fuse.Elements.Alignment.Default;
            temp1.SourceLineNumber = 143;
            temp1.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            global::Fuse.Controls.DockPanel.SetDock(temp1, Fuse.Layouts.Dock.Left);
            temp1.Font = global::MainView.AGOTHIC14;
            temp1.Bindings.Add(temp14);
            temp5.SourceLineNumber = 143;
            temp5.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp2.FontSize = 15f;
            temp2.Alignment = Fuse.Elements.Alignment.Default;
            temp2.SourceLineNumber = 144;
            temp2.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            global::Fuse.Controls.DockPanel.SetDock(temp2, Fuse.Layouts.Dock.Left);
            temp2.Font = global::MainView.AGOTHIC14;
            temp2.Bindings.Add(temp15);
            temp6.SourceLineNumber = 144;
            temp6.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp3.FontSize = 15f;
            temp3.TextAlignment = Fuse.Controls.TextAlignment.Right;
            temp3.Width = new Uno.UX.Size(50f, Uno.UX.Unit.Unspecified);
            temp3.MinWidth = new Uno.UX.Size(50f, Uno.UX.Unit.Unspecified);
            temp3.MaxWidth = new Uno.UX.Size(80f, Uno.UX.Unit.Unspecified);
            temp3.Alignment = Fuse.Elements.Alignment.Default;
            temp3.SourceLineNumber = 145;
            temp3.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            global::Fuse.Controls.DockPanel.SetDock(temp3, Fuse.Layouts.Dock.Right);
            temp3.Font = global::MainView.AGOTHIC14;
            temp3.Bindings.Add(temp16);
            temp12.SourceLineNumber = 145;
            temp12.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp7.SourceLineNumber = 145;
            temp7.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp11.SourceLineNumber = 145;
            temp11.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp9.SourceLineNumber = 145;
            temp9.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp10.SourceLineNumber = 145;
            temp10.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp17.SourceLineNumber = 146;
            temp17.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp17.Animators.Add(temp18);
            temp18.Y = 1f;
            temp18.Duration = 0.8;
            temp18.RelativeTo = Fuse.Triggers.LayoutTransition.PositionLayoutChange;
            temp18.Easing = Fuse.Animations.Easing.ElasticIn;
            temp19.SourceLineNumber = 150;
            temp19.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp19.Animators.Add(temp20);
            temp20.X = 1f;
            temp20.Duration = 0.3;
            temp20.RelativeTo = Fuse.TranslationModes.Size;
            temp20.Easing = Fuse.Animations.Easing.CircularIn;
            temp21.SourceLineNumber = 154;
            temp21.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp21.Animators.Add(temp22);
            temp22.X = -1f;
            temp22.Duration = 0.4;
            temp22.RelativeTo = Fuse.TranslationModes.Size;
            temp22.Easing = Fuse.Animations.Easing.CircularOut;
            __self.Children.Add(temp);
            __self.Children.Add(temp1);
            __self.Children.Add(temp2);
            __self.Children.Add(temp3);
            __self.Children.Add(temp17);
            __self.Children.Add(temp19);
            __self.Children.Add(temp21);
            return __self;
        }
        static global::Uno.UX.Selector __selector0 = "Value";
    }
    [Uno.Compiler.UxGenerated]
    public partial class Template1: Uno.UX.Template
    {
        [Uno.WeakReference] internal readonly c_gr __parent;
        [Uno.WeakReference] internal readonly c_gr __parentInstance;
        public Template1(c_gr parent, c_gr parentInstance): base(null, false)
        {
            __parent = parent;
            __parentInstance = parentInstance;
        }
        global::Uno.UX.Property<string> temp_Value_inst;
        global::Uno.UX.Property<string> temp1_Value_inst;
        global::Uno.UX.Property<string> temp2_Value_inst;
        static Template1()
        {
        }
        public override object New()
        {
            var __self = new global::Fuse.Controls.DockPanel();
            var temp = new global::Fuse.Controls.Text();
            temp_Value_inst = new HSMRO_FuseControlsTextControl_Value_Property(temp, __selector0);
            var temp3 = new global::Fuse.Reactive.Data("gr_spec");
            var temp1 = new global::Fuse.Controls.Text();
            temp1_Value_inst = new HSMRO_FuseControlsTextControl_Value_Property(temp1, __selector0);
            var temp4 = new global::Fuse.Reactive.Data("gr_maker");
            var temp2 = new global::Fuse.Controls.Text();
            temp2_Value_inst = new HSMRO_FuseControlsTextControl_Value_Property(temp2, __selector0);
            var temp5 = new global::Fuse.Reactive.Data("gr_po_no");
            var temp6 = new global::Fuse.Reactive.DataBinding(temp_Value_inst, temp3, Fuse.Reactive.BindingMode.Default);
            var temp7 = new global::Fuse.Reactive.DataBinding(temp1_Value_inst, temp4, Fuse.Reactive.BindingMode.Default);
            var temp8 = new global::Fuse.Reactive.DataBinding(temp2_Value_inst, temp5, Fuse.Reactive.BindingMode.Default);
            var temp9 = new global::Fuse.Triggers.LayoutAnimation();
            var temp10 = new global::Fuse.Animations.Move();
            var temp11 = new global::Fuse.Triggers.AddingAnimation();
            var temp12 = new global::Fuse.Animations.Move();
            var temp13 = new global::Fuse.Triggers.RemovingAnimation();
            var temp14 = new global::Fuse.Animations.Move();
            __self.Width = new Uno.UX.Size(100f, Uno.UX.Unit.Percent);
            __self.Height = new Uno.UX.Size(40f, Uno.UX.Unit.Unspecified);
            __self.Alignment = Fuse.Elements.Alignment.Default;
            __self.Margin = float4(0f, 0f, 0f, 0f);
            __self.Padding = float4(10f, 0f, 10f, 0f);
            __self.SourceLineNumber = 159;
            __self.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp.FontSize = 13f;
            temp.Alignment = Fuse.Elements.Alignment.Default;
            temp.SourceLineNumber = 160;
            temp.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            global::Fuse.Controls.DockPanel.SetDock(temp, Fuse.Layouts.Dock.Left);
            temp.Font = global::MainView.AGOTHIC14;
            temp.Bindings.Add(temp6);
            temp3.SourceLineNumber = 160;
            temp3.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp1.FontSize = 13f;
            temp1.Alignment = Fuse.Elements.Alignment.Default;
            temp1.Margin = float4(10f, 0f, 0f, 0f);
            temp1.SourceLineNumber = 161;
            temp1.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            global::Fuse.Controls.DockPanel.SetDock(temp1, Fuse.Layouts.Dock.Left);
            temp1.Font = global::MainView.AGOTHIC14;
            temp1.Bindings.Add(temp7);
            temp4.SourceLineNumber = 161;
            temp4.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp2.FontSize = 13f;
            temp2.Alignment = Fuse.Elements.Alignment.Default;
            temp2.Margin = float4(10f, 0f, 0f, 0f);
            temp2.SourceLineNumber = 162;
            temp2.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            global::Fuse.Controls.DockPanel.SetDock(temp2, Fuse.Layouts.Dock.Left);
            temp2.Font = global::MainView.AGOTHIC14;
            temp2.Bindings.Add(temp8);
            temp5.SourceLineNumber = 162;
            temp5.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp9.SourceLineNumber = 163;
            temp9.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp9.Animators.Add(temp10);
            temp10.Y = 1f;
            temp10.Duration = 0.8;
            temp10.RelativeTo = Fuse.Triggers.LayoutTransition.PositionLayoutChange;
            temp10.Easing = Fuse.Animations.Easing.ElasticIn;
            temp11.SourceLineNumber = 167;
            temp11.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp11.Animators.Add(temp12);
            temp12.X = 1f;
            temp12.Duration = 0.3;
            temp12.RelativeTo = Fuse.TranslationModes.Size;
            temp12.Easing = Fuse.Animations.Easing.CircularIn;
            temp13.SourceLineNumber = 171;
            temp13.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp13.Animators.Add(temp14);
            temp14.X = -1f;
            temp14.Duration = 0.4;
            temp14.RelativeTo = Fuse.TranslationModes.Size;
            temp14.Easing = Fuse.Animations.Easing.CircularOut;
            __self.Children.Add(temp);
            __self.Children.Add(temp1);
            __self.Children.Add(temp2);
            __self.Children.Add(temp9);
            __self.Children.Add(temp11);
            __self.Children.Add(temp13);
            return __self;
        }
        static global::Uno.UX.Selector __selector0 = "Value";
    }
    [Uno.Compiler.UxGenerated]
    public partial class Template2: Uno.UX.Template
    {
        [Uno.WeakReference] internal readonly c_gr __parent;
        [Uno.WeakReference] internal readonly c_gr __parentInstance;
        public Template2(c_gr parent, c_gr parentInstance): base(null, false)
        {
            __parent = parent;
            __parentInstance = parentInstance;
        }
        static Template2()
        {
        }
        public override object New()
        {
            var __self = new global::Fuse.Controls.Rectangle();
            __self.Color = float4(0.772549f, 0.7843137f, 0.9333333f, 1f);
            __self.Height = new Uno.UX.Size(1f, Uno.UX.Unit.Unspecified);
            __self.Margin = float4(0f, -10f, 0f, 0f);
            __self.SourceLineNumber = 175;
            __self.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            global::Fuse.Controls.DockPanel.SetDock(__self, Fuse.Layouts.Dock.Top);
            return __self;
        }
    }
    [Uno.Compiler.UxGenerated]
    public partial class Template3: Uno.UX.Template
    {
        [Uno.WeakReference] internal readonly c_gr __parent;
        [Uno.WeakReference] internal readonly c_gr __parentInstance;
        public Template3(c_gr parent, c_gr parentInstance): base(null, false)
        {
            __parent = parent;
            __parentInstance = parentInstance;
        }
        global::Uno.UX.Property<string> temp_Value_inst;
        global::Uno.UX.Property<string> temp1_Value_inst;
        global::Uno.UX.Property<string> temp2_Value_inst;
        static Template3()
        {
        }
        public override object New()
        {
            var __self = new global::Fuse.Controls.DockPanel();
            var temp = new global::Fuse.Controls.Text();
            temp_Value_inst = new HSMRO_FuseControlsTextControl_Value_Property(temp, __selector0);
            var temp3 = new global::Fuse.Reactive.Data("gr_item_cd2");
            var temp1 = new global::Fuse.Controls.Text();
            temp1_Value_inst = new HSMRO_FuseControlsTextControl_Value_Property(temp1, __selector0);
            var temp4 = new global::Fuse.Reactive.Data("gr_item_nm2");
            var temp5 = new global::Fuse.Reactive.Data("gr_qty2");
            var temp6 = " ";
            var temp7 = new global::Fuse.Reactive.Constant(temp6);
            var temp8 = new global::Fuse.Reactive.Data("gr_unit2");
            var temp9 = new global::Fuse.Reactive.Add(temp7, temp8);
            var temp2 = new global::Fuse.Controls.Text();
            temp2_Value_inst = new HSMRO_FuseControlsTextControl_Value_Property(temp2, __selector0);
            var temp10 = new global::Fuse.Reactive.Add(temp5, temp9);
            var temp11 = new global::Fuse.Reactive.DataBinding(temp_Value_inst, temp3, Fuse.Reactive.BindingMode.Default);
            var temp12 = new global::Fuse.Reactive.DataBinding(temp1_Value_inst, temp4, Fuse.Reactive.BindingMode.Default);
            var temp13 = new global::Fuse.Reactive.DataBinding(temp2_Value_inst, temp10, Fuse.Reactive.BindingMode.Default);
            var temp14 = new global::Fuse.Triggers.LayoutAnimation();
            var temp15 = new global::Fuse.Animations.Move();
            var temp16 = new global::Fuse.Triggers.AddingAnimation();
            var temp17 = new global::Fuse.Animations.Move();
            __self.Width = new Uno.UX.Size(100f, Uno.UX.Unit.Percent);
            __self.Alignment = Fuse.Elements.Alignment.Default;
            __self.Margin = float4(0f, 0f, 0f, 10f);
            __self.Padding = float4(10f, 0f, 10f, 0f);
            __self.SourceLineNumber = 236;
            __self.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp.FontSize = 12f;
            temp.Alignment = Fuse.Elements.Alignment.Default;
            temp.SourceLineNumber = 237;
            temp.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            global::Fuse.Controls.DockPanel.SetDock(temp, Fuse.Layouts.Dock.Left);
            temp.Font = global::MainView.AGOTHIC14;
            temp.Bindings.Add(temp11);
            temp3.SourceLineNumber = 237;
            temp3.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp1.FontSize = 12f;
            temp1.Alignment = Fuse.Elements.Alignment.Default;
            temp1.Margin = float4(15f, 0f, 0f, 0f);
            temp1.SourceLineNumber = 238;
            temp1.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            global::Fuse.Controls.DockPanel.SetDock(temp1, Fuse.Layouts.Dock.Left);
            temp1.Font = global::MainView.AGOTHIC14;
            temp1.Bindings.Add(temp12);
            temp4.SourceLineNumber = 238;
            temp4.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp2.FontSize = 12f;
            temp2.Alignment = Fuse.Elements.Alignment.Default;
            temp2.Margin = float4(0f, 0f, 10f, 0f);
            temp2.SourceLineNumber = 239;
            temp2.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            global::Fuse.Controls.DockPanel.SetDock(temp2, Fuse.Layouts.Dock.Right);
            temp2.Font = global::MainView.AGOTHIC14;
            temp2.Bindings.Add(temp13);
            temp10.SourceLineNumber = 239;
            temp10.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp5.SourceLineNumber = 239;
            temp5.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp9.SourceLineNumber = 239;
            temp9.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp7.SourceLineNumber = 239;
            temp7.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp8.SourceLineNumber = 239;
            temp8.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp14.SourceLineNumber = 240;
            temp14.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp14.Animators.Add(temp15);
            temp15.Y = 1f;
            temp15.Duration = 0.8;
            temp15.RelativeTo = Fuse.Triggers.LayoutTransition.PositionLayoutChange;
            temp15.Easing = Fuse.Animations.Easing.ElasticIn;
            temp16.SourceLineNumber = 244;
            temp16.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp16.Animators.Add(temp17);
            temp17.Y = 1f;
            temp17.Duration = 0.5;
            temp17.RelativeTo = Fuse.TranslationModes.Size;
            temp17.Easing = Fuse.Animations.Easing.CircularIn;
            __self.Children.Add(temp);
            __self.Children.Add(temp1);
            __self.Children.Add(temp2);
            __self.Children.Add(temp14);
            __self.Children.Add(temp16);
            return __self;
        }
        static global::Uno.UX.Selector __selector0 = "Value";
    }
    [Uno.Compiler.UxGenerated]
    public partial class Template4: Uno.UX.Template
    {
        [Uno.WeakReference] internal readonly c_gr __parent;
        [Uno.WeakReference] internal readonly c_gr __parentInstance;
        public Template4(c_gr parent, c_gr parentInstance): base(null, false)
        {
            __parent = parent;
            __parentInstance = parentInstance;
        }
        global::Uno.UX.Property<string> temp_Value_inst;
        global::Uno.UX.Property<string> temp1_Value_inst;
        global::Uno.UX.Property<string> temp2_Value_inst;
        static Template4()
        {
        }
        public override object New()
        {
            var __self = new global::Fuse.Controls.DockPanel();
            var temp = new global::Fuse.Controls.Text();
            temp_Value_inst = new HSMRO_FuseControlsTextControl_Value_Property(temp, __selector0);
            var temp3 = new global::Fuse.Reactive.Data("gr_spec2");
            var temp1 = new global::Fuse.Controls.Text();
            temp1_Value_inst = new HSMRO_FuseControlsTextControl_Value_Property(temp1, __selector0);
            var temp4 = new global::Fuse.Reactive.Data("gr_maker2");
            var temp2 = new global::Fuse.Controls.Text();
            temp2_Value_inst = new HSMRO_FuseControlsTextControl_Value_Property(temp2, __selector0);
            var temp5 = new global::Fuse.Reactive.Data("gr_po_no2");
            var temp6 = new global::Fuse.Reactive.DataBinding(temp_Value_inst, temp3, Fuse.Reactive.BindingMode.Default);
            var temp7 = new global::Fuse.Reactive.DataBinding(temp1_Value_inst, temp4, Fuse.Reactive.BindingMode.Default);
            var temp8 = new global::Fuse.Reactive.DataBinding(temp2_Value_inst, temp5, Fuse.Reactive.BindingMode.Default);
            var temp9 = new global::Fuse.Triggers.LayoutAnimation();
            var temp10 = new global::Fuse.Animations.Move();
            var temp11 = new global::Fuse.Triggers.AddingAnimation();
            var temp12 = new global::Fuse.Animations.Move();
            __self.Width = new Uno.UX.Size(100f, Uno.UX.Unit.Percent);
            __self.Alignment = Fuse.Elements.Alignment.Default;
            __self.Margin = float4(0f, 0f, 0f, 5f);
            __self.Padding = float4(10f, 0f, 10f, 0f);
            __self.SourceLineNumber = 248;
            __self.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp.FontSize = 11f;
            temp.Alignment = Fuse.Elements.Alignment.Default;
            temp.SourceLineNumber = 249;
            temp.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            global::Fuse.Controls.DockPanel.SetDock(temp, Fuse.Layouts.Dock.Left);
            temp.Font = global::MainView.AGOTHIC14;
            temp.Bindings.Add(temp6);
            temp3.SourceLineNumber = 249;
            temp3.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp1.FontSize = 11f;
            temp1.Alignment = Fuse.Elements.Alignment.Default;
            temp1.Margin = float4(10f, 0f, 0f, 0f);
            temp1.SourceLineNumber = 250;
            temp1.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            global::Fuse.Controls.DockPanel.SetDock(temp1, Fuse.Layouts.Dock.Left);
            temp1.Font = global::MainView.AGOTHIC14;
            temp1.Bindings.Add(temp7);
            temp4.SourceLineNumber = 250;
            temp4.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp2.FontSize = 11f;
            temp2.Alignment = Fuse.Elements.Alignment.Default;
            temp2.Margin = float4(10f, 0f, 0f, 0f);
            temp2.SourceLineNumber = 251;
            temp2.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            global::Fuse.Controls.DockPanel.SetDock(temp2, Fuse.Layouts.Dock.Left);
            temp2.Font = global::MainView.AGOTHIC14;
            temp2.Bindings.Add(temp8);
            temp5.SourceLineNumber = 251;
            temp5.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp9.SourceLineNumber = 254;
            temp9.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp9.Animators.Add(temp10);
            temp10.Y = 1f;
            temp10.Duration = 0.8;
            temp10.RelativeTo = Fuse.Triggers.LayoutTransition.PositionLayoutChange;
            temp10.Easing = Fuse.Animations.Easing.ElasticIn;
            temp11.SourceLineNumber = 258;
            temp11.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            temp11.Animators.Add(temp12);
            temp12.Y = 1f;
            temp12.Duration = 0.5;
            temp12.RelativeTo = Fuse.TranslationModes.Size;
            temp12.Easing = Fuse.Animations.Easing.CircularIn;
            __self.Children.Add(temp);
            __self.Children.Add(temp1);
            __self.Children.Add(temp2);
            __self.Children.Add(temp9);
            __self.Children.Add(temp11);
            return __self;
        }
        static global::Uno.UX.Selector __selector0 = "Value";
    }
    [Uno.Compiler.UxGenerated]
    public partial class Template5: Uno.UX.Template
    {
        [Uno.WeakReference] internal readonly c_gr __parent;
        [Uno.WeakReference] internal readonly c_gr __parentInstance;
        public Template5(c_gr parent, c_gr parentInstance): base(null, false)
        {
            __parent = parent;
            __parentInstance = parentInstance;
        }
        static Template5()
        {
        }
        public override object New()
        {
            var __self = new global::Fuse.Controls.Rectangle();
            __self.Color = float4(0.772549f, 0.7843137f, 0.9333333f, 1f);
            __self.Height = new Uno.UX.Size(1f, Uno.UX.Unit.Unspecified);
            __self.Margin = float4(0f, 0f, 0f, 10f);
            __self.SourceLineNumber = 262;
            __self.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
            global::Fuse.Controls.DockPanel.SetDock(__self, Fuse.Layouts.Dock.Top);
            return __self;
        }
    }
    global::Uno.UX.Property<string> temp_Value_inst;
    global::Uno.UX.Property<string> temp1_Value_inst;
    global::Uno.UX.Property<string> temp2_Value_inst;
    global::Uno.UX.Property<string> temp3_Value_inst;
    global::Uno.UX.Property<string> temp4_Value_inst;
    global::Uno.UX.Property<Fuse.Visual> navigation_Active_inst;
    global::Uno.UX.Property<Fuse.Drawing.Brush> tab1_Background_inst;
    global::Uno.UX.Property<string> tab1_Color_inst;
    global::Uno.UX.Property<Uno.DateTime> dtpk1_Value_inst;
    global::Uno.UX.Property<Uno.DateTime> dtpk1_MinValue_inst;
    global::Uno.UX.Property<Uno.DateTime> dtpk1_MaxValue_inst;
    global::Uno.UX.Property<bool> temp5_Value_inst;
    global::Uno.UX.Property<bool> isBusy_IsActive_inst;
    global::Uno.UX.Property<float> loadingPanel_Opacity_inst;
    global::Uno.UX.Property<bool> temp6_Value_inst;
    global::Uno.UX.Property<Fuse.Elements.Visibility> temp7_Visibility_inst;
    global::Uno.UX.Property<string> txt1_Value_inst;
    global::Uno.UX.Property<string> in_dt1_Value_inst;
    global::Uno.UX.Property<object> temp8_Items_inst;
    global::Uno.UX.Property<Fuse.Elements.Visibility> temp9_Visibility_inst;
    global::Uno.UX.Property<Fuse.Elements.Element> indicator_Element_LayoutMaster_inst;
    global::Uno.UX.Property<float4> indicator_Color_inst;
    global::Uno.UX.Property<object> temp10_Items_inst;
    internal global::Fuse.Reactive.EventBinding temp_eb34;
    internal global::Fuse.Controls.Rectangle indicator;
    internal global::Fuse.Controls.Panel page1Tab;
    internal global::Tab tab1;
    internal global::Fuse.Controls.PageControl navigation;
    internal global::Fuse.Controls.Page page1;
    internal global::Fuse.Controls.DatePicker dtpk1;
    internal global::Fuse.Triggers.Busy isBusy;
    internal global::MyLoadingIndicator1 loadingPanel;
    internal global::Fuse.Controls.Text txt1;
    internal global::Fuse.Controls.Text in_dt1;
    internal global::Fuse.Reactive.EventBinding temp_eb35;
    internal global::Fuse.Reactive.EventBinding temp_eb36;
    internal global::Fuse.Reactive.EventBinding temp_eb37;
    internal global::Fuse.Reactive.EventBinding temp_eb38;
    internal global::Fuse.Reactive.EventBinding temp_eb39;
    internal global::Fuse.Reactive.EventBinding temp_eb40;
    internal global::Fuse.Controls.Page page2;
    global::Uno.UX.NameTable __g_nametable;
    static string[] __g_static_nametable = new string[] {
        "temp_eb34",
        "router",
        "indicator",
        "page1Tab",
        "tab1",
        "navigation",
        "page1",
        "dtpk1",
        "isBusy",
        "loadingPanel",
        "txt1",
        "in_dt1",
        "temp_eb35",
        "temp_eb36",
        "temp_eb37",
        "temp_eb38",
        "temp_eb39",
        "temp_eb40",
        "page2"
    };
    static c_gr()
    {
    }
    [global::Uno.UX.UXConstructor]
    public c_gr(
		[global::Uno.UX.UXParameter("router")] Fuse.Navigation.Router router)
    {
        this.router = router;
        InitializeUX();
    }
    void InitializeUX()
    {
        var temp11 = new global::Fuse.Reactive.Data("backBtn");
        __g_nametable = new global::Uno.UX.NameTable(null, __g_static_nametable);
        var temp = new global::Fuse.Controls.Text();
        temp_Value_inst = new HSMRO_FuseControlsTextControl_Value_Property(temp, __selector0);
        var temp12 = new global::Fuse.Reactive.Data("g_DATE_DD");
        var temp1 = new global::Fuse.Controls.Text();
        temp1_Value_inst = new HSMRO_FuseControlsTextControl_Value_Property(temp1, __selector0);
        var temp13 = new global::Fuse.Reactive.Data("g_DATE_YM");
        var temp2 = new global::Fuse.Controls.Text();
        temp2_Value_inst = new HSMRO_FuseControlsTextControl_Value_Property(temp2, __selector0);
        var temp14 = new global::Fuse.Reactive.Data("g_DATE_DAY");
        var temp3 = new global::Fuse.Controls.Text();
        temp3_Value_inst = new HSMRO_FuseControlsTextControl_Value_Property(temp3, __selector0);
        var temp15 = new global::Fuse.Reactive.Data("g_BP_NM_obs");
        var temp4 = new global::Fuse.Controls.Text();
        temp4_Value_inst = new HSMRO_FuseControlsTextControl_Value_Property(temp4, __selector0);
        var temp16 = new global::Fuse.Reactive.Data("g_USR_NM_obs");
        navigation = new global::Fuse.Controls.PageControl();
        navigation_Active_inst = new HSMRO_FuseControlsNavigationControl_Active_Property(navigation, __selector1);
        tab1 = new global::Tab();
        tab1_Background_inst = new HSMRO_FuseControlsControl_Background_Property(tab1, __selector2);
        tab1_Color_inst = new HSMRO_Tab_Color_Property(tab1, __selector3);
        dtpk1 = new global::Fuse.Controls.DatePicker();
        dtpk1_Value_inst = new HSMRO_FuseControlsDatePickerBase_Value_Property(dtpk1, __selector0);
        var temp17 = new global::Fuse.Reactive.Data("someDate");
        dtpk1_MinValue_inst = new HSMRO_FuseControlsDatePickerBase_MinValue_Property(dtpk1, __selector4);
        var temp18 = new global::Fuse.Reactive.Data("minDate");
        dtpk1_MaxValue_inst = new HSMRO_FuseControlsDatePickerBase_MaxValue_Property(dtpk1, __selector5);
        var temp19 = new global::Fuse.Reactive.Data("maxDate");
        var temp5 = new global::Fuse.Triggers.WhileTrue();
        temp5_Value_inst = new HSMRO_FuseTriggersWhileBool_Value_Property(temp5, __selector0);
        var temp20 = new global::Fuse.Reactive.Data("dtpk1_visible");
        isBusy = new global::Fuse.Triggers.Busy();
        isBusy_IsActive_inst = new HSMRO_FuseTriggersBusy_IsActive_Property(isBusy, __selector6);
        var temp21 = new global::Fuse.Reactive.Data("isBusy");
        loadingPanel = new global::MyLoadingIndicator1();
        loadingPanel_Opacity_inst = new HSMRO_FuseElementsElement_Opacity_Property(loadingPanel, __selector7);
        var temp6 = new global::Fuse.Triggers.WhileTrue();
        temp6_Value_inst = new HSMRO_FuseTriggersWhileBool_Value_Property(temp6, __selector0);
        var temp22 = new global::Fuse.Reactive.Data("isBusy");
        var temp7 = new global::Fuse.Controls.Text();
        temp7_Visibility_inst = new HSMRO_FuseElementsElement_Visibility_Property(temp7, __selector8);
        var temp23 = new global::Fuse.Reactive.Data("device");
        txt1 = new global::Fuse.Controls.Text();
        txt1_Value_inst = new HSMRO_FuseControlsTextControl_Value_Property(txt1, __selector0);
        var temp24 = new global::Fuse.Reactive.Data("txt");
        in_dt1 = new global::Fuse.Controls.Text();
        in_dt1_Value_inst = new HSMRO_FuseControlsTextControl_Value_Property(in_dt1, __selector0);
        var temp25 = new global::Fuse.Reactive.Data("in_dt");
        var temp26 = new global::Fuse.Reactive.Data("clk_in_dt1");
        var temp27 = new global::Fuse.Reactive.Data("clk_in_dt1");
        var temp28 = new global::Fuse.Reactive.Data("scanBar");
        var temp8 = new global::Fuse.Reactive.Each();
        temp8_Items_inst = new HSMRO_FuseReactiveEach_Items_Property(temp8, __selector9);
        var temp29 = new global::Fuse.Reactive.Data("gr_list");
        var temp30 = new global::Fuse.Reactive.Data("sendBtn");
        var temp31 = new global::Fuse.Reactive.Data("clrBtn");
        var temp32 = new global::Fuse.Reactive.Data("backBtn_ios");
        var temp9 = new global::Fuse.Controls.Button();
        temp9_Visibility_inst = new HSMRO_FuseElementsElement_Visibility_Property(temp9, __selector8);
        var temp33 = new global::Fuse.Reactive.Data("device");
        indicator = new global::Fuse.Controls.Rectangle();
        indicator_Element_LayoutMaster_inst = new HSMRO_FuseElementsElement_ElementLayoutMaster_Property(indicator, __selector10);
        indicator_Color_inst = new HSMRO_FuseControlsShape_Color_Property(indicator, __selector3);
        var temp10 = new global::Fuse.Reactive.Each();
        temp10_Items_inst = new HSMRO_FuseReactiveEach_Items_Property(temp10, __selector9);
        var temp34 = new global::Fuse.Reactive.Data("gr_list2");
        var temp35 = new global::Fuse.Navigation.WhileActive();
        var temp36 = new global::Fuse.Triggers.OnBackButton();
        temp_eb34 = new global::Fuse.Reactive.EventBinding(temp11);
        var temp37 = new global::Fuse.Reactive.JavaScript(__g_nametable);
        var temp38 = new global::Fuse.Triggers.LayoutAnimation();
        var temp39 = new global::Fuse.Animations.Move();
        var temp40 = new global::Fuse.Controls.Panel();
        var temp41 = new global::Fuse.Controls.DockPanel();
        var temp42 = new global::Fuse.Controls.Rectangle();
        var temp43 = new global::Fuse.Controls.Grid();
        var temp44 = new global::Fuse.Controls.Image();
        var temp45 = new global::Fuse.Reactive.DataBinding(temp_Value_inst, temp12, Fuse.Reactive.BindingMode.Default);
        var temp46 = new global::Fuse.Controls.WrapPanel();
        var temp47 = new global::Fuse.Reactive.DataBinding(temp1_Value_inst, temp13, Fuse.Reactive.BindingMode.Default);
        var temp48 = new global::Fuse.Reactive.DataBinding(temp2_Value_inst, temp14, Fuse.Reactive.BindingMode.Default);
        var temp49 = new global::Fuse.Controls.Grid();
        var temp50 = new global::Fuse.Controls.WrapPanel();
        var temp51 = new global::Fuse.Reactive.DataBinding(temp3_Value_inst, temp15, Fuse.Reactive.BindingMode.Default);
        var temp52 = new global::Fuse.Reactive.DataBinding(temp4_Value_inst, temp16, Fuse.Reactive.BindingMode.Default);
        var temp53 = new global::Fuse.Controls.Image();
        var temp54 = new global::Fuse.Drawing.LinearGradient();
        var temp55 = new global::Fuse.Drawing.GradientStop();
        var temp56 = new global::Fuse.Drawing.GradientStop();
        var temp57 = new global::Fuse.Controls.Grid();
        page1Tab = new global::Fuse.Controls.Panel();
        var temp58 = new global::Fuse.Drawing.StaticSolidColor(float4(1f, 1f, 1f, 1f));
        var temp59 = new global::Fuse.Gestures.Clicked();
        var temp60 = new global::Fuse.Triggers.Actions.Set<Fuse.Visual>(navigation_Active_inst);
        var temp61 = new global::Fuse.Triggers.Actions.Set<Fuse.Drawing.Brush>(tab1_Background_inst);
        var temp62 = new global::Fuse.Drawing.StaticSolidColor(float4(1f, 1f, 1f, 1f));
        var temp63 = new global::Fuse.Triggers.Actions.Set<string>(tab1_Color_inst);
        var temp64 = new global::Fuse.Drawing.StaticSolidColor(float4(1f, 1f, 1f, 1f));
        page1 = new global::Fuse.Controls.Page();
        var temp65 = new global::Fuse.Controls.NativeViewHost();
        var temp66 = new global::Fuse.Reactive.DataBinding(dtpk1_Value_inst, temp17, Fuse.Reactive.BindingMode.Default);
        var temp67 = new global::Fuse.Reactive.DataBinding(dtpk1_MinValue_inst, temp18, Fuse.Reactive.BindingMode.Default);
        var temp68 = new global::Fuse.Reactive.DataBinding(dtpk1_MaxValue_inst, temp19, Fuse.Reactive.BindingMode.Default);
        var temp69 = new global::Fuse.Reactive.DataBinding(temp5_Value_inst, temp20, Fuse.Reactive.BindingMode.Default);
        var temp70 = new global::Fuse.Controls.Panel();
        var temp71 = new global::Fuse.Reactive.DataBinding(isBusy_IsActive_inst, temp21, Fuse.Reactive.BindingMode.Default);
        var temp72 = new global::Fuse.Triggers.WhileBusy();
        var temp73 = new global::Fuse.Animations.Change<float>(loadingPanel_Opacity_inst);
        var temp74 = new global::Fuse.Reactive.DataBinding(temp6_Value_inst, temp22, Fuse.Reactive.BindingMode.Default);
        var temp75 = new global::Fuse.Controls.DockPanel();
        var temp76 = new global::Fuse.Reactive.DataBinding(temp7_Visibility_inst, temp23, Fuse.Reactive.BindingMode.Default);
        var temp77 = new global::Fuse.Controls.DockPanel();
        var temp78 = new global::Fuse.Controls.DockPanel();
        var temp79 = new global::Fuse.Controls.WrapPanel();
        var temp80 = new global::Fuse.Controls.Text();
        var temp81 = new global::Fuse.Controls.Rectangle();
        var temp82 = new global::Fuse.Reactive.DataBinding(txt1_Value_inst, temp24, Fuse.Reactive.BindingMode.Default);
        var temp83 = new global::Fuse.Controls.WrapPanel();
        var temp84 = new global::Fuse.Controls.Text();
        var temp85 = new global::Fuse.Reactive.DataBinding(in_dt1_Value_inst, temp25, Fuse.Reactive.BindingMode.Default);
        temp_eb35 = new global::Fuse.Reactive.EventBinding(temp26);
        var temp86 = new global::Fuse.Controls.Image();
        temp_eb36 = new global::Fuse.Reactive.EventBinding(temp27);
        var temp87 = new global::Fuse.Controls.Button();
        var temp88 = new global::Fuse.Controls.Image();
        var temp89 = new global::Fuse.Gestures.WhilePressed();
        var temp90 = new global::Fuse.Animations.Scale();
        temp_eb37 = new global::Fuse.Reactive.EventBinding(temp28);
        var temp91 = new global::Fuse.Controls.ScrollView();
        var temp92 = new global::Fuse.Controls.StackPanel();
        var temp93 = new Template(this, this);
        var temp94 = new Template1(this, this);
        var temp95 = new Template2(this, this);
        var temp96 = new global::Fuse.Reactive.DataBinding(temp8_Items_inst, temp29, Fuse.Reactive.BindingMode.Default);
        var temp97 = new global::Fuse.Controls.DockPanel();
        var temp98 = new global::Fuse.Controls.Rectangle();
        var temp99 = new global::Fuse.Controls.Button();
        var temp100 = new global::Fuse.Controls.Grid();
        var temp101 = new global::Fuse.Controls.Image();
        var temp102 = new global::Fuse.Controls.Text();
        temp_eb38 = new global::Fuse.Reactive.EventBinding(temp30);
        var temp103 = new global::Fuse.Gestures.WhilePressed();
        var temp104 = new global::Fuse.Animations.Scale();
        var temp105 = new global::Fuse.Drawing.Stroke();
        var temp106 = new global::Fuse.Controls.Rectangle();
        var temp107 = new global::Fuse.Controls.Button();
        var temp108 = new global::Fuse.Controls.Grid();
        var temp109 = new global::Fuse.Controls.Image();
        var temp110 = new global::Fuse.Controls.Text();
        temp_eb39 = new global::Fuse.Reactive.EventBinding(temp31);
        var temp111 = new global::Fuse.Gestures.WhilePressed();
        var temp112 = new global::Fuse.Animations.Scale();
        var temp113 = new global::Fuse.Drawing.Stroke();
        var temp114 = new global::Fuse.Controls.Image();
        temp_eb40 = new global::Fuse.Reactive.EventBinding(temp32);
        var temp115 = new global::Fuse.Reactive.DataBinding(temp9_Visibility_inst, temp33, Fuse.Reactive.BindingMode.Default);
        var temp116 = new global::Fuse.Navigation.WhileActive();
        var temp117 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Element>(indicator_Element_LayoutMaster_inst);
        var temp118 = new global::Fuse.Triggers.Actions.Set<float4>(indicator_Color_inst);
        var temp119 = new global::Fuse.Triggers.Actions.Set<Fuse.Drawing.Brush>(tab1_Background_inst);
        var temp120 = new global::Fuse.Drawing.StaticSolidColor(float4(1f, 1f, 1f, 1f));
        var temp121 = new global::Fuse.Triggers.Actions.Set<string>(tab1_Color_inst);
        var temp122 = new global::Fuse.Drawing.StaticSolidColor(float4(1f, 1f, 1f, 1f));
        page2 = new global::Fuse.Controls.Page();
        var temp123 = new global::Fuse.Controls.DockPanel();
        var temp124 = new global::Fuse.Controls.ScrollView();
        var temp125 = new global::Fuse.Controls.StackPanel();
        var temp126 = new global::CogWheelReload();
        var temp127 = new Template3(this, this);
        var temp128 = new Template4(this, this);
        var temp129 = new Template5(this, this);
        var temp130 = new global::Fuse.Reactive.DataBinding(temp10_Items_inst, temp34, Fuse.Reactive.BindingMode.Default);
        var temp131 = new global::Fuse.Controls.WrapPanel();
        var temp132 = new global::Fuse.Controls.Text();
        var temp133 = new global::Fuse.Controls.Text();
        var temp134 = new global::Fuse.Navigation.WhileActive();
        var temp135 = new global::Fuse.Triggers.Actions.Set<float4>(indicator_Color_inst);
        var temp136 = new global::Fuse.Triggers.Actions.Set<Fuse.Drawing.Brush>(tab1_Background_inst);
        var temp137 = new global::Fuse.Drawing.StaticSolidColor(float4(0.5450981f, 0.4470588f, 0.7607843f, 1f));
        var temp138 = new global::Fuse.Triggers.Actions.Set<string>(tab1_Color_inst);
        var temp139 = new global::Fuse.Drawing.StaticSolidColor(float4(1f, 1f, 1f, 1f));
        var temp140 = new global::Fuse.Controls.BottomBarBackground();
        this.Alignment = Fuse.Elements.Alignment.Default;
        this.Name = __selector11;
        this.SourceLineNumber = 1;
        this.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp35.SourceLineNumber = 2;
        temp35.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp35.Nodes.Add(temp36);
        temp36.SourceLineNumber = 3;
        temp36.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp36.Handler += temp_eb34.OnEvent;
        temp36.Bindings.Add(temp_eb34);
        temp11.SourceLineNumber = 3;
        temp11.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp37.LineNumber = 7;
        temp37.FileName = "Pages/Menu_Customer/c_gr.ux";
        temp37.SourceLineNumber = 7;
        temp37.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp37.File = new global::Uno.UX.BundleFileSource(import("../../Pages/Menu_Customer/c_gr.js"));
        indicator.Color = float4(1f, 1f, 1f, 1f);
        indicator.Height = new Uno.UX.Size(4f, Uno.UX.Unit.Unspecified);
        indicator.Alignment = Fuse.Elements.Alignment.Bottom;
        indicator.Name = __selector12;
        indicator.SourceLineNumber = 9;
        indicator.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        global::Fuse.Controls.LayoutControl.SetLayoutMaster(indicator, page1Tab);
        indicator.Children.Add(temp38);
        temp38.SourceLineNumber = 10;
        temp38.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp38.Animators.Add(temp39);
        temp39.X = 1f;
        temp39.Duration = 0.3;
        temp39.RelativeTo = Fuse.Triggers.LayoutTransition.WorldPositionChange;
        temp39.Easing = Fuse.Animations.Easing.BackIn;
        temp40.Alignment = Fuse.Elements.Alignment.Default;
        temp40.SourceLineNumber = 14;
        temp40.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        global::Fuse.Controls.DockPanel.SetDock(temp40, Fuse.Layouts.Dock.Fill);
        temp40.Children.Add(temp41);
        temp41.Alignment = Fuse.Elements.Alignment.Default;
        temp41.SourceLineNumber = 20;
        temp41.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp41.Children.Add(temp42);
        temp41.Children.Add(temp57);
        temp41.Children.Add(navigation);
        temp41.Children.Add(temp140);
        temp42.Height = new Uno.UX.Size(100f, Uno.UX.Unit.Unspecified);
        temp42.Alignment = Fuse.Elements.Alignment.Default;
        temp42.Margin = float4(0f, 0f, 0f, 0f);
        temp42.Padding = float4(0f, 10f, 0f, 0f);
        temp42.Opacity = 1f;
        temp42.SourceLineNumber = 21;
        temp42.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        global::Fuse.Controls.DockPanel.SetDock(temp42, Fuse.Layouts.Dock.Top);
        temp42.Fills.Add(temp54);
        temp42.Children.Add(temp43);
        temp42.Children.Add(temp49);
        temp43.RowCount = 1;
        temp43.Columns = "40,1*, auto";
        temp43.ColumnCount = 3;
        temp43.CellSpacing = 1f;
        temp43.Width = new Uno.UX.Size(160f, Uno.UX.Unit.Unspecified);
        temp43.Height = new Uno.UX.Size(100f, Uno.UX.Unit.Percent);
        temp43.MinWidth = new Uno.UX.Size(160f, Uno.UX.Unit.Unspecified);
        temp43.Alignment = Fuse.Elements.Alignment.Left;
        temp43.Padding = float4(10f, 5f, 5f, 5f);
        temp43.SourceLineNumber = 22;
        temp43.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        global::Fuse.Controls.DockPanel.SetDock(temp43, Fuse.Layouts.Dock.Left);
        temp43.Children.Add(temp44);
        temp43.Children.Add(temp);
        temp43.Children.Add(temp46);
        temp44.Width = new Uno.UX.Size(60f, Uno.UX.Unit.Unspecified);
        temp44.Height = new Uno.UX.Size(60f, Uno.UX.Unit.Unspecified);
        temp44.Alignment = Fuse.Elements.Alignment.Center;
        temp44.Margin = float4(0f, 0f, 0f, 0f);
        temp44.Padding = float4(0f, 0f, 0f, 0f);
        temp44.SourceLineNumber = 23;
        temp44.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        global::Fuse.Controls.Grid.SetRow(temp44, 0);
        global::Fuse.Controls.Grid.SetColumn(temp44, 0);
        temp44.File = new global::Uno.UX.BundleFileSource(import("../../Assets/Icons/calendar.png"));
        temp.FontSize = 40f;
        temp.TextColor = float4(1f, 1f, 1f, 1f);
        temp.Alignment = Fuse.Elements.Alignment.Center;
        temp.Padding = float4(0f, 0f, 0f, 0f);
        temp.SourceLineNumber = 24;
        temp.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp.Font = global::MainView.AGOTHIC14;
        temp.Bindings.Add(temp45);
        temp12.SourceLineNumber = 24;
        temp12.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp46.Orientation = Fuse.Layouts.Orientation.Vertical;
        temp46.Alignment = Fuse.Elements.Alignment.Center;
        temp46.SourceLineNumber = 25;
        temp46.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp46.Children.Add(temp1);
        temp46.Children.Add(temp2);
        temp1.FontSize = 15f;
        temp1.TextColor = float4(1f, 1f, 1f, 1f);
        temp1.Alignment = Fuse.Elements.Alignment.CenterLeft;
        temp1.SourceLineNumber = 26;
        temp1.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp1.Font = global::MainView.AGOTHIC14;
        temp1.Bindings.Add(temp47);
        temp13.SourceLineNumber = 26;
        temp13.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp2.FontSize = 13f;
        temp2.TextColor = float4(1f, 1f, 1f, 1f);
        temp2.Alignment = Fuse.Elements.Alignment.CenterLeft;
        temp2.SourceLineNumber = 27;
        temp2.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp2.Font = global::MainView.AGOTHIC14;
        temp2.Bindings.Add(temp48);
        temp14.SourceLineNumber = 27;
        temp14.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp49.Columns = "auto, 40";
        temp49.ColumnCount = 2;
        temp49.CellSpacing = 7f;
        temp49.Width = new Uno.UX.Size(160f, Uno.UX.Unit.Unspecified);
        temp49.MinWidth = new Uno.UX.Size(160f, Uno.UX.Unit.Unspecified);
        temp49.Alignment = Fuse.Elements.Alignment.Right;
        temp49.Margin = float4(0f, 0f, 5f, 0f);
        temp49.Padding = float4(10f, 5f, 5f, 5f);
        temp49.SourceLineNumber = 30;
        temp49.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        global::Fuse.Controls.DockPanel.SetDock(temp49, Fuse.Layouts.Dock.Right);
        temp49.Children.Add(temp50);
        temp49.Children.Add(temp53);
        temp50.Orientation = Fuse.Layouts.Orientation.Vertical;
        temp50.Alignment = Fuse.Elements.Alignment.Center;
        temp50.Margin = float4(0f, 0f, 0f, 0f);
        temp50.SourceLineNumber = 31;
        temp50.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp50.Children.Add(temp3);
        temp50.Children.Add(temp4);
        temp3.FontSize = 15f;
        temp3.TextAlignment = Fuse.Controls.TextAlignment.Right;
        temp3.TextColor = float4(1f, 1f, 1f, 1f);
        temp3.Alignment = Fuse.Elements.Alignment.Right;
        temp3.SourceLineNumber = 32;
        temp3.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp3.Font = global::MainView.AGOTHIC14;
        temp3.Bindings.Add(temp51);
        temp15.SourceLineNumber = 32;
        temp15.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp4.FontSize = 13f;
        temp4.TextAlignment = Fuse.Controls.TextAlignment.Right;
        temp4.TextColor = float4(1f, 1f, 1f, 1f);
        temp4.Alignment = Fuse.Elements.Alignment.Right;
        temp4.SourceLineNumber = 33;
        temp4.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp4.Font = global::MainView.AGOTHIC14;
        temp4.Bindings.Add(temp52);
        temp16.SourceLineNumber = 33;
        temp16.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp53.Width = new Uno.UX.Size(60f, Uno.UX.Unit.Unspecified);
        temp53.Height = new Uno.UX.Size(60f, Uno.UX.Unit.Unspecified);
        temp53.Alignment = Fuse.Elements.Alignment.Default;
        temp53.Margin = float4(0f, 0f, 0f, 0f);
        temp53.Padding = float4(0f, 0f, 0f, 0f);
        temp53.SourceLineNumber = 35;
        temp53.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp53.File = new global::Uno.UX.BundleFileSource(import("../../Assets/Icons/user.png"));
        temp54.Stops.Add(temp55);
        temp54.Stops.Add(temp56);
        temp55.Offset = 0f;
        temp55.Color = float4(0.2784314f, 0.2509804f, 0.7058824f, 1f);
        temp56.Offset = 1f;
        temp56.Color = float4(0.5490196f, 0.4509804f, 0.7607843f, 1f);
        temp57.ColumnCount = 1;
        temp57.Height = new Uno.UX.Size(50f, Uno.UX.Unit.Unspecified);
        temp57.Alignment = Fuse.Elements.Alignment.Default;
        temp57.SourceLineNumber = 43;
        temp57.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        global::Fuse.Controls.DockPanel.SetDock(temp57, Fuse.Layouts.Dock.Top);
        temp57.Background = temp64;
        temp57.Children.Add(page1Tab);
        page1Tab.Name = __selector13;
        page1Tab.SourceLineNumber = 44;
        page1Tab.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        page1Tab.Children.Add(tab1);
        page1Tab.Children.Add(temp59);
        tab1.Text = "입고등록";
        tab1.Color = "#ffffff";
        tab1.Name = __selector14;
        tab1.SourceLineNumber = 45;
        tab1.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        tab1.Background = temp58;
        temp59.SourceLineNumber = 46;
        temp59.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp59.Actions.Add(temp60);
        temp59.Actions.Add(temp61);
        temp59.Actions.Add(temp63);
        temp60.Value = page1;
        temp60.SourceLineNumber = 47;
        temp60.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp61.Value = temp62;
        temp61.SourceLineNumber = 48;
        temp61.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp63.Value = "#000000";
        temp63.SourceLineNumber = 51;
        temp63.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        navigation.Interaction = Fuse.Controls.NavigationControlInteraction.None;
        navigation.Alignment = Fuse.Elements.Alignment.Default;
        navigation.Name = __selector15;
        navigation.SourceLineNumber = 70;
        navigation.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        global::Fuse.Controls.DockPanel.SetDock(navigation, Fuse.Layouts.Dock.Fill);
        navigation.Children.Add(page1);
        navigation.Children.Add(page2);
        page1.Alignment = Fuse.Elements.Alignment.Default;
        page1.Padding = float4(10f, 10f, 10f, 10f);
        page1.Name = __selector16;
        page1.SourceLineNumber = 72;
        page1.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        page1.Background = temp122;
        page1.Children.Add(temp5);
        page1.Children.Add(temp6);
        page1.Children.Add(temp75);
        page1.Children.Add(temp116);
        temp5.SourceLineNumber = 73;
        temp5.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp5.Nodes.Add(temp65);
        temp5.Bindings.Add(temp69);
        temp65.SourceLineNumber = 74;
        temp65.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp65.Children.Add(dtpk1);
        dtpk1.Layer = Fuse.Layer.Overlay;
        dtpk1.Name = __selector17;
        dtpk1.SourceLineNumber = 75;
        dtpk1.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        dtpk1.Background = Fuse.Drawing.Brushes.White;
        dtpk1.Bindings.Add(temp66);
        dtpk1.Bindings.Add(temp67);
        dtpk1.Bindings.Add(temp68);
        temp17.SourceLineNumber = 75;
        temp17.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp18.SourceLineNumber = 75;
        temp18.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp19.SourceLineNumber = 75;
        temp19.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp20.SourceLineNumber = 73;
        temp20.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp6.SourceLineNumber = 78;
        temp6.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp6.Nodes.Add(temp70);
        temp6.Bindings.Add(temp74);
        temp70.HitTestMode = Fuse.Elements.HitTestMode.LocalBounds;
        temp70.SourceLineNumber = 95;
        temp70.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp70.Children.Add(isBusy);
        temp70.Children.Add(temp72);
        temp70.Children.Add(loadingPanel);
        isBusy.Name = __selector18;
        isBusy.SourceLineNumber = 96;
        isBusy.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        isBusy.Bindings.Add(temp71);
        temp21.SourceLineNumber = 96;
        temp21.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp72.SourceLineNumber = 97;
        temp72.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp72.Animators.Add(temp73);
        temp73.Value = 1f;
        temp73.Duration = 0.4;
        loadingPanel.ThemeColor = float4(0.3372549f, 0f, 0.9176471f, 1f);
        loadingPanel.Opacity = 0f;
        loadingPanel.Name = __selector19;
        loadingPanel.SourceLineNumber = 100;
        loadingPanel.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp22.SourceLineNumber = 78;
        temp22.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp75.SourceLineNumber = 104;
        temp75.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp75.Children.Add(temp7);
        temp75.Children.Add(temp77);
        temp75.Children.Add(temp91);
        temp75.Children.Add(temp97);
        temp7.Value = "거래명세서 우측 상단 QR코드를 스캔하세요";
        temp7.FontSize = 14f;
        temp7.TextAlignment = Fuse.Controls.TextAlignment.Center;
        temp7.Color = float4(1f, 0.3411765f, 0.5568628f, 1f);
        temp7.Width = new Uno.UX.Size(100f, Uno.UX.Unit.Percent);
        temp7.Alignment = Fuse.Elements.Alignment.Center;
        temp7.SourceLineNumber = 108;
        temp7.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        global::Fuse.Controls.DockPanel.SetDock(temp7, Fuse.Layouts.Dock.Top);
        temp7.Font = global::MainView.AGOTHIC14;
        temp7.Bindings.Add(temp76);
        temp23.SourceLineNumber = 108;
        temp23.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp77.Width = new Uno.UX.Size(100f, Uno.UX.Unit.Percent);
        temp77.Height = new Uno.UX.Size(100f, Uno.UX.Unit.Unspecified);
        temp77.Alignment = Fuse.Elements.Alignment.Top;
        temp77.Margin = float4(0f, 5f, 0f, 0f);
        temp77.Padding = float4(5f, 5f, 5f, 5f);
        temp77.SourceLineNumber = 109;
        temp77.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        global::Fuse.Controls.DockPanel.SetDock(temp77, Fuse.Layouts.Dock.Top);
        temp77.Children.Add(temp78);
        temp77.Children.Add(temp87);
        temp78.Width = new Uno.UX.Size(80f, Uno.UX.Unit.Percent);
        temp78.Alignment = Fuse.Elements.Alignment.Default;
        temp78.SourceLineNumber = 111;
        temp78.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        global::Fuse.Controls.DockPanel.SetDock(temp78, Fuse.Layouts.Dock.Left);
        temp78.Children.Add(temp79);
        temp78.Children.Add(temp83);
        temp79.Orientation = Fuse.Layouts.Orientation.Horizontal;
        temp79.Alignment = Fuse.Elements.Alignment.Default;
        temp79.Margin = float4(0f, 0f, 0f, 0f);
        temp79.SourceLineNumber = 112;
        temp79.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        global::Fuse.Controls.DockPanel.SetDock(temp79, Fuse.Layouts.Dock.Top);
        temp79.Children.Add(temp80);
        temp79.Children.Add(temp81);
        temp80.Value = "명세서번호";
        temp80.FontSize = 15f;
        temp80.TextAlignment = Fuse.Controls.TextAlignment.Left;
        temp80.Width = new Uno.UX.Size(80f, Uno.UX.Unit.Unspecified);
        temp80.Height = new Uno.UX.Size(30f, Uno.UX.Unit.Unspecified);
        temp80.Alignment = Fuse.Elements.Alignment.Default;
        temp80.Margin = float4(0f, 0f, 0f, 0f);
        temp80.SourceLineNumber = 113;
        temp80.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        global::Fuse.Controls.DockPanel.SetDock(temp80, Fuse.Layouts.Dock.Top);
        temp80.Font = global::MainView.AGOTHIC14;
        temp81.Width = new Uno.UX.Size(180f, Uno.UX.Unit.Unspecified);
        temp81.Height = new Uno.UX.Size(30f, Uno.UX.Unit.Unspecified);
        temp81.Margin = float4(0f, 0f, 0f, 10f);
        temp81.SourceLineNumber = 114;
        temp81.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp81.Children.Add(txt1);
        txt1.FontSize = 15f;
        txt1.TextAlignment = Fuse.Controls.TextAlignment.Left;
        txt1.Width = new Uno.UX.Size(180f, Uno.UX.Unit.Unspecified);
        txt1.Height = new Uno.UX.Size(30f, Uno.UX.Unit.Unspecified);
        txt1.Alignment = Fuse.Elements.Alignment.Center;
        txt1.Margin = float4(5f, 10f, 0f, 0f);
        txt1.Name = __selector20;
        txt1.SourceLineNumber = 115;
        txt1.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        global::Fuse.Controls.DockPanel.SetDock(txt1, Fuse.Layouts.Dock.Top);
        txt1.Font = global::MainView.AGOTHIC14;
        txt1.Bindings.Add(temp82);
        temp24.SourceLineNumber = 115;
        temp24.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp83.Orientation = Fuse.Layouts.Orientation.Horizontal;
        temp83.Alignment = Fuse.Elements.Alignment.CenterLeft;
        temp83.Margin = float4(0f, 0f, 0f, 0f);
        temp83.SourceLineNumber = 124;
        temp83.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        global::Fuse.Controls.DockPanel.SetDock(temp83, Fuse.Layouts.Dock.Top);
        temp83.Children.Add(temp84);
        temp83.Children.Add(in_dt1);
        temp83.Children.Add(temp86);
        temp84.Value = "입고일자";
        temp84.FontSize = 15f;
        temp84.TextAlignment = Fuse.Controls.TextAlignment.Left;
        temp84.Width = new Uno.UX.Size(80f, Uno.UX.Unit.Unspecified);
        temp84.Height = new Uno.UX.Size(30f, Uno.UX.Unit.Unspecified);
        temp84.Alignment = Fuse.Elements.Alignment.Default;
        temp84.Margin = float4(0f, 0f, 0f, 0f);
        temp84.SourceLineNumber = 125;
        temp84.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        global::Fuse.Controls.DockPanel.SetDock(temp84, Fuse.Layouts.Dock.Top);
        temp84.Font = global::MainView.AGOTHIC14;
        in_dt1.FontSize = 15f;
        in_dt1.TextAlignment = Fuse.Controls.TextAlignment.Left;
        in_dt1.Width = new Uno.UX.Size(100f, Uno.UX.Unit.Percent);
        in_dt1.Height = new Uno.UX.Size(30f, Uno.UX.Unit.Unspecified);
        in_dt1.Alignment = Fuse.Elements.Alignment.Default;
        in_dt1.Margin = float4(0f, 0f, 0f, 0f);
        in_dt1.Name = __selector21;
        in_dt1.SourceLineNumber = 126;
        in_dt1.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        global::Fuse.Controls.DockPanel.SetDock(in_dt1, Fuse.Layouts.Dock.Top);
        global::Fuse.Gestures.Clicked.AddHandler(in_dt1, temp_eb35.OnEvent);
        in_dt1.Font = global::MainView.AGOTHIC14;
        in_dt1.Bindings.Add(temp85);
        in_dt1.Bindings.Add(temp_eb35);
        temp25.SourceLineNumber = 126;
        temp25.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp26.SourceLineNumber = 126;
        temp26.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp86.Width = new Uno.UX.Size(40f, Uno.UX.Unit.Unspecified);
        temp86.Height = new Uno.UX.Size(40f, Uno.UX.Unit.Unspecified);
        temp86.Alignment = Fuse.Elements.Alignment.Default;
        temp86.Margin = float4(0f, 0f, 0f, 13f);
        temp86.SourceLineNumber = 127;
        temp86.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        global::Fuse.Gestures.Clicked.AddHandler(temp86, temp_eb36.OnEvent);
        temp86.File = new global::Uno.UX.BundleFileSource(import("../../Assets/Icons/date1.png"));
        temp86.Bindings.Add(temp_eb36);
        temp27.SourceLineNumber = 127;
        temp27.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp87.Width = new Uno.UX.Size(40f, Uno.UX.Unit.Unspecified);
        temp87.Height = new Uno.UX.Size(40f, Uno.UX.Unit.Unspecified);
        temp87.Alignment = Fuse.Elements.Alignment.Default;
        temp87.Margin = float4(0f, 0f, 0f, 0f);
        temp87.SourceLineNumber = 130;
        temp87.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        global::Fuse.Controls.DockPanel.SetDock(temp87, Fuse.Layouts.Dock.Top);
        global::Fuse.Gestures.Clicked.AddHandler(temp87, temp_eb37.OnEvent);
        temp87.Children.Add(temp88);
        temp87.Children.Add(temp89);
        temp87.Bindings.Add(temp_eb37);
        temp88.Width = new Uno.UX.Size(100f, Uno.UX.Unit.Unspecified);
        temp88.Height = new Uno.UX.Size(100f, Uno.UX.Unit.Unspecified);
        temp88.Alignment = Fuse.Elements.Alignment.Default;
        temp88.Margin = float4(0f, 0f, 0f, 0f);
        temp88.Padding = float4(0f, 0f, 0f, 0f);
        temp88.SourceLineNumber = 131;
        temp88.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        global::Fuse.Controls.DockPanel.SetDock(temp88, Fuse.Layouts.Dock.Fill);
        temp88.File = new global::Uno.UX.BundleFileSource(import("../../Assets/Icons/scanQR.png"));
        temp89.SourceLineNumber = 132;
        temp89.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp89.Animators.Add(temp90);
        temp90.Factor = 0.95f;
        temp90.Duration = 0.08;
        temp90.Easing = Fuse.Animations.Easing.QuadraticOut;
        temp28.SourceLineNumber = 130;
        temp28.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp91.Alignment = Fuse.Elements.Alignment.Default;
        temp91.Margin = float4(0f, 10f, 0f, 0f);
        temp91.SourceLineNumber = 137;
        temp91.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        global::Fuse.Controls.DockPanel.SetDock(temp91, Fuse.Layouts.Dock.Fill);
        temp91.Children.Add(temp92);
        temp92.Width = new Uno.UX.Size(100f, Uno.UX.Unit.Percent);
        temp92.SourceLineNumber = 138;
        temp92.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp92.Children.Add(temp8);
        temp8.SourceLineNumber = 139;
        temp8.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp8.Templates.Add(temp93);
        temp8.Templates.Add(temp94);
        temp8.Templates.Add(temp95);
        temp8.Bindings.Add(temp96);
        temp29.SourceLineNumber = 139;
        temp29.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp97.Alignment = Fuse.Elements.Alignment.HorizontalCenter;
        temp97.Margin = float4(60f, 0f, 0f, 10f);
        temp97.SourceLineNumber = 180;
        temp97.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        global::Fuse.Controls.DockPanel.SetDock(temp97, Fuse.Layouts.Dock.Bottom);
        temp97.Children.Add(temp98);
        temp97.Children.Add(temp106);
        temp97.Children.Add(temp9);
        temp98.CornerRadius = float4(10f, 10f, 10f, 10f);
        temp98.Width = new Uno.UX.Size(120f, Uno.UX.Unit.Unspecified);
        temp98.Height = new Uno.UX.Size(50f, Uno.UX.Unit.Unspecified);
        temp98.Margin = float4(0f, 0f, 0f, 0f);
        temp98.SourceLineNumber = 182;
        temp98.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        global::Fuse.Controls.DockPanel.SetDock(temp98, Fuse.Layouts.Dock.Left);
        temp98.Strokes.Add(temp105);
        temp98.Children.Add(temp99);
        temp98.Children.Add(temp103);
        temp99.Width = new Uno.UX.Size(120f, Uno.UX.Unit.Unspecified);
        temp99.Height = new Uno.UX.Size(50f, Uno.UX.Unit.Unspecified);
        temp99.SourceLineNumber = 183;
        temp99.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        global::Fuse.Controls.DockPanel.SetDock(temp99, Fuse.Layouts.Dock.Left);
        global::Fuse.Gestures.Clicked.AddHandler(temp99, temp_eb38.OnEvent);
        temp99.Children.Add(temp100);
        temp99.Bindings.Add(temp_eb38);
        temp100.RowCount = 1;
        temp100.Columns = "50, auto";
        temp100.ColumnCount = 2;
        temp100.SourceLineNumber = 184;
        temp100.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp100.Children.Add(temp101);
        temp100.Children.Add(temp102);
        temp101.Width = new Uno.UX.Size(50f, Uno.UX.Unit.Unspecified);
        temp101.Height = new Uno.UX.Size(50f, Uno.UX.Unit.Unspecified);
        temp101.Alignment = Fuse.Elements.Alignment.CenterLeft;
        temp101.SourceLineNumber = 185;
        temp101.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp101.File = new global::Uno.UX.BundleFileSource(import("../../Assets/Icons/check.png"));
        temp102.Value = "입고등록";
        temp102.Color = float4(0.3372549f, 0f, 0.9176471f, 1f);
        temp102.Alignment = Fuse.Elements.Alignment.CenterLeft;
        temp102.SourceLineNumber = 186;
        temp102.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp102.Font = global::MainView.AGOTHIC14;
        temp30.SourceLineNumber = 183;
        temp30.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp103.SourceLineNumber = 189;
        temp103.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp103.Animators.Add(temp104);
        temp104.Factor = 0.95f;
        temp104.Duration = 0.08;
        temp104.Easing = Fuse.Animations.Easing.QuadraticOut;
        temp105.Color = float4(0.3372549f, 0f, 0.9176471f, 1f);
        temp105.Width = 1f;
        temp106.CornerRadius = float4(10f, 10f, 10f, 10f);
        temp106.Width = new Uno.UX.Size(120f, Uno.UX.Unit.Unspecified);
        temp106.Height = new Uno.UX.Size(50f, Uno.UX.Unit.Unspecified);
        temp106.Margin = float4(5f, 0f, 0f, 0f);
        temp106.SourceLineNumber = 196;
        temp106.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        global::Fuse.Controls.DockPanel.SetDock(temp106, Fuse.Layouts.Dock.Left);
        temp106.Strokes.Add(temp113);
        temp106.Children.Add(temp107);
        temp106.Children.Add(temp111);
        temp107.Width = new Uno.UX.Size(120f, Uno.UX.Unit.Unspecified);
        temp107.Height = new Uno.UX.Size(50f, Uno.UX.Unit.Unspecified);
        temp107.SourceLineNumber = 197;
        temp107.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        global::Fuse.Controls.DockPanel.SetDock(temp107, Fuse.Layouts.Dock.Left);
        global::Fuse.Gestures.Clicked.AddHandler(temp107, temp_eb39.OnEvent);
        temp107.Children.Add(temp108);
        temp107.Bindings.Add(temp_eb39);
        temp108.RowCount = 1;
        temp108.Columns = "50, auto";
        temp108.ColumnCount = 2;
        temp108.SourceLineNumber = 198;
        temp108.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp108.Children.Add(temp109);
        temp108.Children.Add(temp110);
        temp109.Width = new Uno.UX.Size(50f, Uno.UX.Unit.Unspecified);
        temp109.Height = new Uno.UX.Size(50f, Uno.UX.Unit.Unspecified);
        temp109.Alignment = Fuse.Elements.Alignment.CenterLeft;
        temp109.SourceLineNumber = 199;
        temp109.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp109.File = new global::Uno.UX.BundleFileSource(import("../../Assets/Icons/reset.png"));
        temp110.Value = "초기화";
        temp110.Color = float4(0.3372549f, 0f, 0.9176471f, 1f);
        temp110.Alignment = Fuse.Elements.Alignment.CenterLeft;
        temp110.SourceLineNumber = 200;
        temp110.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp110.Font = global::MainView.AGOTHIC14;
        temp31.SourceLineNumber = 197;
        temp31.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp111.SourceLineNumber = 203;
        temp111.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp111.Animators.Add(temp112);
        temp112.Factor = 0.95f;
        temp112.Duration = 0.08;
        temp112.Easing = Fuse.Animations.Easing.QuadraticOut;
        temp113.Color = float4(0.3372549f, 0f, 0.9176471f, 1f);
        temp113.Width = 1f;
        temp9.Width = new Uno.UX.Size(50f, Uno.UX.Unit.Unspecified);
        temp9.Height = new Uno.UX.Size(50f, Uno.UX.Unit.Unspecified);
        temp9.Alignment = Fuse.Elements.Alignment.Right;
        temp9.Margin = float4(10f, 0f, 0f, 0f);
        temp9.SourceLineNumber = 208;
        temp9.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        global::Fuse.Controls.DockPanel.SetDock(temp9, Fuse.Layouts.Dock.Right);
        global::Fuse.Gestures.Clicked.AddHandler(temp9, temp_eb40.OnEvent);
        temp9.Children.Add(temp114);
        temp9.Bindings.Add(temp_eb40);
        temp9.Bindings.Add(temp115);
        temp114.Color = float4(0f, 0f, 0f, 0.3490196f);
        temp114.Height = new Uno.UX.Size(20f, Uno.UX.Unit.Unspecified);
        temp114.Alignment = Fuse.Elements.Alignment.Center;
        temp114.SourceLineNumber = 209;
        temp114.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp114.File = new global::Uno.UX.BundleFileSource(import("../../Assets/Icons/back.png"));
        temp32.SourceLineNumber = 208;
        temp32.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp33.SourceLineNumber = 208;
        temp33.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp116.Threshold = 0.5f;
        temp116.SourceLineNumber = 214;
        temp116.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp116.Actions.Add(temp117);
        temp116.Actions.Add(temp118);
        temp116.Actions.Add(temp119);
        temp116.Actions.Add(temp121);
        temp117.Value = page1Tab;
        temp117.SourceLineNumber = 215;
        temp117.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp118.Value = float4(0.5176471f, 0.345098f, 0.8196079f, 1f);
        temp118.SourceLineNumber = 216;
        temp118.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp119.Value = temp120;
        temp119.SourceLineNumber = 217;
        temp119.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp121.Value = "#000000";
        temp121.SourceLineNumber = 219;
        temp121.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        page2.Alignment = Fuse.Elements.Alignment.Default;
        page2.Padding = float4(10f, 10f, 10f, 10f);
        page2.Name = __selector22;
        page2.SourceLineNumber = 224;
        page2.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        page2.Background = temp139;
        page2.Children.Add(temp123);
        page2.Children.Add(temp134);
        temp123.Width = new Uno.UX.Size(100f, Uno.UX.Unit.Percent);
        temp123.Alignment = Fuse.Elements.Alignment.Default;
        temp123.SourceLineNumber = 225;
        temp123.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp123.Children.Add(temp124);
        temp123.Children.Add(temp131);
        temp124.Alignment = Fuse.Elements.Alignment.Default;
        temp124.Margin = float4(0f, 0f, 0f, 0f);
        temp124.SourceLineNumber = 232;
        temp124.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        global::Fuse.Controls.DockPanel.SetDock(temp124, Fuse.Layouts.Dock.Fill);
        temp124.Children.Add(temp125);
        temp125.Width = new Uno.UX.Size(100f, Uno.UX.Unit.Percent);
        temp125.SourceLineNumber = 233;
        temp125.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp125.Children.Add(temp126);
        temp125.Children.Add(temp10);
        temp126.SourceLineNumber = 234;
        temp126.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        global::Fuse.Controls.DockPanel.SetDock(temp126, Fuse.Layouts.Dock.Top);
        temp10.SourceLineNumber = 235;
        temp10.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp10.Templates.Add(temp127);
        temp10.Templates.Add(temp128);
        temp10.Templates.Add(temp129);
        temp10.Bindings.Add(temp130);
        temp34.SourceLineNumber = 235;
        temp34.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp131.Orientation = Fuse.Layouts.Orientation.Vertical;
        temp131.Alignment = Fuse.Elements.Alignment.HorizontalCenter;
        temp131.SourceLineNumber = 266;
        temp131.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        global::Fuse.Controls.DockPanel.SetDock(temp131, Fuse.Layouts.Dock.Bottom);
        temp131.Children.Add(temp132);
        temp131.Children.Add(temp133);
        temp132.Value = "당일 바코드 입고 내역만 표시됩니다.";
        temp132.FontSize = 12f;
        temp132.TextAlignment = Fuse.Controls.TextAlignment.Center;
        temp132.Color = float4(0.4666667f, 0.4784314f, 0.6745098f, 1f);
        temp132.Alignment = Fuse.Elements.Alignment.HorizontalCenter;
        temp132.SourceLineNumber = 267;
        temp132.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp132.Font = global::MainView.AGOTHIC14;
        temp133.Value = "아래로 당기면 새로고침";
        temp133.FontSize = 12f;
        temp133.TextAlignment = Fuse.Controls.TextAlignment.Center;
        temp133.Color = float4(0.4666667f, 0.4784314f, 0.6745098f, 1f);
        temp133.Alignment = Fuse.Elements.Alignment.HorizontalCenter;
        temp133.SourceLineNumber = 268;
        temp133.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp133.Font = global::MainView.AGOTHIC14;
        temp134.Threshold = 0.5f;
        temp134.SourceLineNumber = 272;
        temp134.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp134.Actions.Add(temp135);
        temp134.Actions.Add(temp136);
        temp134.Actions.Add(temp138);
        temp135.Value = float4(0.5176471f, 0.345098f, 0.8196079f, 1f);
        temp135.SourceLineNumber = 273;
        temp135.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp136.Value = temp137;
        temp136.SourceLineNumber = 274;
        temp136.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp138.Value = "#ffffff";
        temp138.SourceLineNumber = 275;
        temp138.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        temp140.SourceLineNumber = 282;
        temp140.SourceFileName = "Pages/Menu_Customer/c_gr.ux";
        global::Fuse.Controls.DockPanel.SetDock(temp140, Fuse.Layouts.Dock.Bottom);
        __g_nametable.This = this;
        __g_nametable.Objects.Add(temp_eb34);
        __g_nametable.Objects.Add(router);
        __g_nametable.Objects.Add(indicator);
        __g_nametable.Objects.Add(page1Tab);
        __g_nametable.Objects.Add(tab1);
        __g_nametable.Objects.Add(navigation);
        __g_nametable.Objects.Add(page1);
        __g_nametable.Objects.Add(dtpk1);
        __g_nametable.Objects.Add(isBusy);
        __g_nametable.Objects.Add(loadingPanel);
        __g_nametable.Objects.Add(txt1);
        __g_nametable.Objects.Add(in_dt1);
        __g_nametable.Objects.Add(temp_eb35);
        __g_nametable.Objects.Add(temp_eb36);
        __g_nametable.Objects.Add(temp_eb37);
        __g_nametable.Objects.Add(temp_eb38);
        __g_nametable.Objects.Add(temp_eb39);
        __g_nametable.Objects.Add(temp_eb40);
        __g_nametable.Objects.Add(page2);
        this.Children.Add(temp35);
        this.Children.Add(temp37);
        this.Children.Add(indicator);
        this.Children.Add(temp40);
    }
    static global::Uno.UX.Selector __selector0 = "Value";
    static global::Uno.UX.Selector __selector1 = "Active";
    static global::Uno.UX.Selector __selector2 = "Background";
    static global::Uno.UX.Selector __selector3 = "Color";
    static global::Uno.UX.Selector __selector4 = "MinValue";
    static global::Uno.UX.Selector __selector5 = "MaxValue";
    static global::Uno.UX.Selector __selector6 = "IsActive";
    static global::Uno.UX.Selector __selector7 = "Opacity";
    static global::Uno.UX.Selector __selector8 = "Visibility";
    static global::Uno.UX.Selector __selector9 = "Items";
    static global::Uno.UX.Selector __selector10 = "Element.LayoutMaster";
    static global::Uno.UX.Selector __selector11 = "c_gr";
    static global::Uno.UX.Selector __selector12 = "indicator";
    static global::Uno.UX.Selector __selector13 = "page1Tab";
    static global::Uno.UX.Selector __selector14 = "tab1";
    static global::Uno.UX.Selector __selector15 = "navigation";
    static global::Uno.UX.Selector __selector16 = "page1";
    static global::Uno.UX.Selector __selector17 = "dtpk1";
    static global::Uno.UX.Selector __selector18 = "isBusy";
    static global::Uno.UX.Selector __selector19 = "loadingPanel";
    static global::Uno.UX.Selector __selector20 = "txt1";
    static global::Uno.UX.Selector __selector21 = "in_dt1";
    static global::Uno.UX.Selector __selector22 = "page2";
}
